#!/usr/bin/env bash

###############################################
#23/04/2018
#
#Component for Pipeline script for the variants prioritization project
# Singletons distribution calculation
#v 0.1
###############################################

#by region, selected using bed files generated by a main script test so we can use jobs array

# 1) For each region, count the number of singletons (bash)
# 2) report the region and the singleton number (bash)
# 3) generate a summary with distribution informations (R) 


chr=$1
start=$2
end=$3
infile=$4
outfolder=$5
#window=$6
#window size is defined in the interval provided
# window=$[end - start]
# window=1000000000
#read a whole bed file

# chr=17
# start=46350927
# end=46400927
# win_size=50000
# outfolder=/home/cocca/analyses/VPP_GR2018/15052018_test1/${chr}
# infile=/home/cocca/analyses/paperONE/supp_data/pop_subset/03012018/VBI/${chr}.vcf.gz

#read a single region
# echo "vcftools --gzvcf ${infile} --chr ${chr} --from-bp ${start} --to-bp ${end} --TajimaD ${window} --out ${outfolder}/${chr}.${start}-${end}"
vcftools --gzvcf ${infile} --chr ${chr} --from-bp ${start} --to-bp ${end} --min-alleles 2 --max-alleles 2 --singletons --out ${outfolder}/${chr}.${start}-${end}

nsites=`bcftools view -H -r ${chr}:${start}-${end} -m2 -M2 ${infile} | wc -l | cut -f 1 -d " "`

line_num=`wc -l ${outfolder}/${chr}.${start}-${end}.singletons | cut -f 1 -d " "`

if [[ ${line_num} -eq 1 ]];then
#we have an empty region file, but we still want to know that there is nothing there, so we nwwd to build a file with something in
# CHROM START END N_SING N_SITES SING_RATE W_size SING_RATE_by_W_size"
    winsize=`echo "${end} - ${start}" | bc`
    echo "${chr} ${start} ${end} 0 0 NA ${winsize} NA"> ${outfolder}/${chr}.${start}-${end}.singletons_stats
else
#we can now filter out all the doubletons and get the number 
(fgrep -h -v CHROM ${outfolder}/${chr}.${start}-${end}.singletons |awk '$3=="S"'| awk -v w_s=${start} -v w_e=${end} -v nsites_reg=${nsites} '{n++}END{if(nsites_reg != 0 ) print $1,w_s,w_e,n,nsites_reg,n/nsites_reg,w_e-w_s,n/(w_e-w_s);else print $1,w_s,w_e,n,nsites_reg,"NA",w_e-w_s,n/(w_e-w_s)}') | tr "\t" " "> ${outfolder}/${chr}.${start}-${end}.singletons_stats
    
fi



